
; Used instructions
%define I_STATE_ENTER 1
%define I_STATE_LEAVE 1
%define I_CELL_FETCH 1
%define I_CELL_PUSH 1
%define I_CELL_READ 1
%define I_CELL_INIT 1
%define I_CELL_POP 1
%define I_GMDLS_SAMPLE 1
%define I_ADDSUB 1
%define I_FPUTNEXT 1
%define I_RANDOM 1
%define I_BUFFER_LOAD_WITH_OFFSET 1
%define I_BUFFER_LOAD 1
%define I_BUFFER_STORE_AND_STEP 1
%define I_BUFFER_ALLOC 1
%define I_PLAY_INSTRUMENT1 1
%define I_PLAY_INSTRUMENT2 1
%define I_PLAY_INSTRUMENT3 1
%define I_KILL 1
%define I_EXP2_BODY 1
%define I_FDONE 1
%define I_FOP 15
%define I_PROC 1
%define I_PROC_CALL 75
%define I_CONSTANT 50
%define I_NOTE_PROPERTY 3
%define I_STACK_LOAD 20
%define I_STACK_STORE 20
%define I_LABEL 1
%define I_IF 1
%define I_LOOPJUMP 1
%define I_ENDIF 1
%define I_ELSE 1
%define I_ROUND 4
%define I_COMPARE 7

%define COMPACT_IMPLICIT_OPCODES 1

%define MAIN_STATIC_PROC_ID 0
%define MAIN_DYNAMIC_PROC_ID 1

%define NUM_PARAMETERS 0
