
use std::f64;
use std::str::FromStr;

use lalrpop_util::ParseError;

use crate::ast::*;

grammar;

pub Program: Program = {
	<includes:Include*> <parameters:Parameter*> <members:Member*> => Program {<>},
};

Include: Include = {
	"include" <before:@L> <path:String> <after:@R> => Include {<>},
};

String: String = {
	<s:r"\x22[^\x22]*\x22"> => s[1 .. s.len() - 1].to_string(),
};

Parameter: Parameter = {
	"parameter" <name:Id> <min:SignedNum> "to" <max:SignedNum> <default:ParameterDefault> => Parameter {<>},
};

ParameterDefault: Option<f64> = {
	=> None,
	"=" <value:SignedNum> => Some(value),
};

Member: Member = {
	<context:Context> <kind:MemberKind> <midi:MidiParam*> <name:Id> <inputs:Pattern> "->" <outputs:Pattern> <body:Statement*>
		=> Member {<>},
};

Context: Context = {
	=> Context::Universal,
	"global" => Context::Global,
	"note" => Context::Note,
}

MemberKind: MemberKind = {
	"module" => MemberKind::Module,
	"function" => MemberKind::Function,
	"instrument" => MemberKind::Instrument,
}

Pattern: Pattern = {
	<before:@L> <items:PatternItems> <after:@R> => Pattern {<>},
};

PatternNoParen: Pattern = {
	<before:@L> <items:PatternItemsNoParen> <after:@R> => Pattern {<>},
};

PatternItems: Vec<PatternItem> = {
	<Vec<PatternItem>>,
	"(" <Comma<PatternItem>> ")",
};

PatternItemsNoParen: Vec<PatternItem> = {
	<Comma<PatternItem>>,
};

PatternItem: PatternItem = {
	<name:Id> => PatternItem {
		name,
		item_type: Type::default(),
	},
	<name:Id> <item_type:ExplicitType> => PatternItem {<>},
};

ExplicitType: Type = {
	":" <scope:Scope?> <width:Width?> <value_type:ValueType?> => Type {<>},
};

Scope: Scope = {
	"static" => Scope::Static,
	"dynamic" => Scope::Dynamic,
};

Width: Width = {
	"mono" => Width::Mono,
	"stereo" => Width::Stereo,
	"generic" => Width::Generic,
};

ValueType: ValueType = {
	"number" => ValueType::Number,
	"bool" => ValueType::Bool,
	"buffer" => ValueType::Buffer,
}

Statement: Statement = {
	<node:PatternNoParen> "=" <exp:Expression> => Statement::Assign {<>},
};

Expression: Expression = {
	OrExpression,
	<condition:Box<OrExpression>> "?" <then:Box<Expression>> ":" <otherwise:Box<Expression>>
		=> Expression::Conditional {<>},
	<before:@L> "for" <name:Id> "to" <count:Box<Expression>> <combinator:Id> <body:Box<Expression>>
		=> Expression::For {<>},
	<before:@L> "for" <length:Box<Expression>> <width:Width?> "buffer" <body:Box<Expression>>
		=> Expression::BufferInit {<>},
};

OrExpression = BinOpLevel<OrOp, XorExpression>;

OrOp: BinOpKind = "|" => BinOpKind::Or;

XorExpression = BinOpLevel<XorOp, AndExpression>;

XorOp: BinOpKind = "^" => BinOpKind::Xor;

AndExpression = BinOpLevel<AndOp, CompareExpression>;

AndOp: BinOpKind = "&" => BinOpKind::And;

CompareExpression = BinOpLevel<CompareOp, AdditiveExpression>;

CompareOp: BinOpKind = {
	"==" => BinOpKind::Eq,
	"!=" => BinOpKind::Neq,
	"<" => BinOpKind::Less,
	"<=" => BinOpKind::LessEq,
	">" => BinOpKind::Greater,
	">=" => BinOpKind::GreaterEq,
};

AdditiveExpression = BinOpLevel<AdditiveOp, MultiplicativeExpression>;

AdditiveOp: BinOpKind = {
	"+" => BinOpKind::Add,
	"-" => BinOpKind::Sub,
	"-+" => BinOpKind::AddSub,
};

MultiplicativeExpression = BinOpLevel<MultiplicativeOp, UnaryExpression>;

MultiplicativeOp: BinOpKind = {
	"*" => BinOpKind::Mul,
	"/" => BinOpKind::Div,
};

UnaryExpression: Expression = {
	<op:UnOp<UnaryOp>> <exp:Box<PrimaryExpression>> => Expression::UnOp {<>},
	<exp:Box<UnaryExpression>> "." <name:Id> <args:ParenthesizedExpressions?> <after:@R> => Expression::Call {
		before: exp.pos_before(),
		midi: vec![],
		name,
		args: [*exp].into_iter().chain(args.into_iter().flatten()).collect(),
		after,
	},
	<exp:Box<UnaryExpression>> "." <index:Uint> <after:@R> => Expression::TupleIndex {<>},
	PrimaryExpression,
};

UnaryOp: UnOpKind = {
	"-" => UnOpKind::Neg,
	"!" => UnOpKind::Not,
};

PrimaryExpression: Expression = {
	<before:@L> <value:Num> <after:@R> => Expression::Number {<>},
	<before:@L> <value:Bool> => Expression::Bool {<>},
	<name:Id> => Expression::Variable {<>},
	<before:@L> <midi:MidiArg*> <name:Id> <args:ParenthesizedExpressions> <after:@R> => Expression::Call {<>},
	<before:@L> <elements:ParenthesizedExpressions> <after:@R> => Expression::Tuple {<>},
	<before:@L> "[" <left:Box<Expression>> "," <right:Box<Expression>> "]" <after:@R> => Expression::Merge {<>},
	<before:@L> "{" <elements:Comma<Expression>> "}" <after:@R> => Expression::BufferLiteral {<>},
	<exp:Box<PrimaryExpression>> "[" <index:Box<Expression>> "]" <after:@R> => Expression::BufferIndex {<>},
};

ParenthesizedExpressions: Vec<Expression> = "(" <elements:Comma<Expression>> ")" => elements;

MidiParam: Id = <name:Id> "::" => name;

MidiArg: MidiMapping = {
	<value:Uint> "::" => MidiMapping::Value {
		channel: value as u8,
		start: 0,
		end: 127,
		transpose_to: 0,
	},
	<value:Uint> "{" <range:MidiNoteRangeTranspose> "}" "::" => MidiMapping::Value {
		channel: value as u8,
		start: range.0,
		end: range.1,
		transpose_to: range.2,
	},
	<name:Id> "::" => MidiMapping::Named { name },
};

MidiNoteRangeTranspose: (u8, u8, u8) = {
	<range:MidiNoteRange> => (range.0, range.1, range.0),
	<range:MidiNoteRange> "/" <transpose:MidiNote> => (range.0, range.1, transpose),
};

MidiNoteRange: (u8, u8) = {
	<start:MidiNote> => (start, start),
	".." <end:MidiNote> => (0, end),
	<start:MidiNote> ".." => (start, 127),
	<start:MidiNote> ".." <end:MidiNote> => (start, end),
};

MidiNote: u8 = {
	<pos:@L> <note:r"[A-G][-#][0-9]"> =>? {
		let notebase = match note.as_bytes()[0] {
			b'C' => 0, b'D' => 2, b'E' => 4, b'F' => 5, b'G' => 7, b'A' => 9, b'B' => 11,
			_ => unreachable!(),
		};
		let sharp = if note.as_bytes()[1] == b'#' { 1 } else { 0 };
		let octave = note.as_bytes()[2] - b'0';
		match (notebase, sharp) {
			(4, 1) | (11, 1) => Err(ParseError::InvalidToken { location: pos }),
			_ => Ok(notebase + sharp + octave * 12),
		}
	}
};

SignedNum: f64 = {
	"-" <num:Num> => -num,
	<num:Num> => num,
};

Num: f64 = {
	<pos:@L> <i:Uint> =>? {
		let n = i as f64;
		if n as u64 == i {
			Ok(n)
		} else {
			Err(ParseError::InvalidToken { location: pos })
		}
	},
	DecimalNum,
	HexadecimalNum,
	"inf" => f64::INFINITY,
};

Bool: bool = {
	"false" => false,
	"true" => true,
};

Id: Id = {
	<before:@L> <text:r"[_a-zA-Z][_a-zA-Z0-9]*"> => Id { before, text: text.to_string() },
};

Uint: u64 = <pos:@L> <s:r"0|[1-9][0-9]*"> =>? {
	u64::from_str(s).map_err(|e| ParseError::InvalidToken { location: pos })
};

DecimalNum: f64 = <pos:@L> <s:r"(0|[1-9][0-9]*)[.][0-9]+"> =>? {
	f64::from_str(s).map_err(|e| ParseError::InvalidToken { location: pos })
};

HexadecimalNum: f64 = <pos:@L> <s:r"0x[0-9a-fA-F]+([.][0-9a-fA-F]*)?"> =>? {
	let mut n = 0.0;
	let mut f = 1.0;
	let mut ff = 1.0;
	for c in s.bytes().skip(2) {
		if c == b'.' {
			ff = 1.0 / 16.0;
		} else {
			let digit = match c {
				(b'0' ..= b'9') => c - b'0',
				(b'a' ..= b'f') => 10 + c - b'a',
				(b'A' ..= b'F') => 10 + c - b'A',
				_ => panic!(),
			} as f64;
			n *= 16.0;
			let new_n = n + digit;
			if new_n - n != digit {
				return Err(ParseError::InvalidToken { location: pos });
			}
			n = new_n;
			f *= ff;
		}
	}
	Ok(n * f)
};

Comma<T>: Vec<T> = <v:(<T> ",")*> <e:T?> => v.into_iter().chain(e).collect();

Box<T>: Box<T> = <data:T> => Box::new(data);

Vec<T>: Vec<T> = <item:T> => vec![item];

UnOp<Op>: UnOp = {
	<before:@L> <kind:Op> => UnOp {<>}
}

BinOp<Op>: BinOp = {
	<before:@L> <kind:Op> => BinOp {<>}
}

BinOpLevel<Op, NextLevel>: Expression = {
	<left:Box<BinOpLevel<Op, NextLevel>>> <op:BinOp<Op>> <right:Box<NextLevel>>
		=> Expression::BinOp {<>},
	NextLevel
}
